### ISSUE TITLE
Rename to core-bioimage-io-java

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/core-bioimage-io-java#7]
This repo should be renamed to follow the naming pattern of https://github.com/bioimage-io/core-bioimage-io-python and https://github.com/bioimage-io/spec-bioimage-io

**Comment by tomburke-rse** [comment]
I can't rename the repo and also not the default branch since I'm only a member, not an owner in the org.

**Comment by constantinpape** [comment]
I can rename it.

**Comment by constantinpape** [comment]
Done.
